version: '3.4'

services:
  web:
    image: qijunbo/oss:1.0
    container_name: oss
    volumes:
      - ./app-log:/app-log
      - /home/oss/data:/data
    ports:
      - "10001:8080"
    networks:
      - webnet
    restart: always
    environment:
      CONTEXTPATH: oss
      APP_DB_HOST: 172.31.221.150
      APP_DB_PORT: 3306
      APP_DB_USER: root
      APP_DB_PASSWORD: sunway123###
      APP_DATABASE: oss

networks:
  webnet:
