spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/oss?useSSL=false
    username: root
    password: sunway123###
    driver-class-name: com.mysql.jdbc.Driver 
  jpa:  
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
authorization: sunway
     