server:
  port: 1001
  session:
    timeout: 1800
  context-path: /oss
        
spring:
  profiles:
    active: prod  # prod  and dev;
  http:
    encoding:
      force: true
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
storage:
  root:
    linux: /download/
    windows: d:\download\
     