server:
  port: 8080
  session:
    timeout: 1800
  context-path: /CONTEXTPATH
        
spring:
  profiles:
    active: prod  # prod  and dev;
  http:
    encoding:
      force: true
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    url: jdbc:mysql://APP_DB_HOST:APP_DB_PORT/APP_DATABASE?useSSL=false
    username: APP_DB_USER
    password: APP_DB_PASSWORD
    driver-class-name: com.mysql.jdbc.Driver 
  jpa:  
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

storage:
  root:
    linux: /data/
    windows: d:\data\
     

