server:    
    port: 80
    session:
        timeout: 1800
spring:
  datasource:
    url: jdbc:mysql://221.234.47.149:3307/test?useSSL=false
    username: root
    password: sunway123#
    driver-class-name: com.mysql.jdbc.Driver 
  jpa:  
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
     